"use client";

import { useCallback, useEffect, useState } from "react";
import { AppShell, PageGuard } from "@/components/app-shell";
import {
  Badge,
  Button,
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  ErrorNote,
  Progress,
  Spinner,
  Table,
  TD,
  TH,
  Tabs,
} from "@/components/ui";
import { EmptyState, SyntheticTag, VerificationBadge, heatColor } from "@/components/shared";
import { api } from "@/lib/api";
import { pct } from "@/lib/utils";

type QueueItem = {
  id: string;
  state: string;
  claimed_at: string;
  extracted_from_resume: boolean;
  code: string;
  label: string;
  category: string;
  student_profile_id: string;
  full_name: string;
};

type StudentRow = {
  id: string;
  full_name: string;
  email: string;
  stream: string;
  cgpa: number | null;
  graduation_year: number | null;
  extraction_status: string;
  claimed_count: number;
  cosigned_count: number;
  verified_count: number;
  total_skills: number;
};

type GapSignal = {
  id: string;
  skill_id: string;
  code: string;
  label: string;
  category: string;
  gap_count: number;
  student_count: number;
  demand_score: number;
  severity: string;
  detail: any;
  computed_at: string;
};

type RoleGap = {
  role: string;
  n_students: number;
  avg_readiness: number | null;
  missing_skill_pcts?: { code: string; label?: string; pct_missing: number }[];
};

export default function TpoPage() {
  return (
    <PageGuard role="tpo">
      <TpoView />
    </PageGuard>
  );
}

function TpoView() {
  const [tab, setTab] = useState("queue");
  const [error, setError] = useState<string | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const [queue, setQueue] = useState<QueueItem[]>([]);
  const [students, setStudents] = useState<StudentRow[]>([]);
  const [gaps, setGaps] = useState<GapSignal[]>([]);
  const [roleGaps, setRoleGaps] = useState<RoleGap[]>([]);
  const [placements, setPlacements] = useState<any>(null);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [openStudent, setOpenStudent] = useState<string | null>(null);
  const [studentSkills, setStudentSkills] = useState<any[]>([]);

  const loadAll = useCallback(async () => {
    try {
      const [q, s, g, rg] = await Promise.all([
        api<QueueItem[]>("/tpo/verification-queue"),
        api<StudentRow[]>("/tpo/students"),
        api<GapSignal[]>("/tpo/curriculum-gaps"),
        api<RoleGap[]>("/tpo/role-gaps"),
      ]);
      setQueue(q);
      setStudents(s);
      setGaps(g);
      setRoleGaps(rg);
    } catch (e: any) {
      setError(e.message);
    }
  }, []);

  useEffect(() => {
    loadAll();
  }, [loadAll]);

  useEffect(() => {
    if (tab === "placements") {
      api("/tpo/placements").then(setPlacements).catch((e) => setError(e.message));
    }
  }, [tab]);

  async function cosign(id: string) {
    setBusyId(id);
    setError(null);
    try {
      const r = await api("/tpo/cosign", {
        method: "POST",
        body: JSON.stringify({ student_skill_id: id, note: "Verified against records by TPO" }),
      });
      setToast(`Skill co-signed (${r.state}) — industry can now verify it; matches recomputed.`);
      await loadAll();
    } catch (e: any) {
      setError(e.message);
    } finally {
      setBusyId(null);
    }
  }

  async function showStudent(profileId: string) {
    if (openStudent === profileId) {
      setOpenStudent(null);
      return;
    }
    try {
      const res = await api<{ skills: any[] }>(`/tpo/students/${profileId}`);
      setStudentSkills(res.skills);
      setOpenStudent(profileId);
    } catch (e: any) {
      setError(e.message);
    }
  }

  const high = gaps.filter((g) => g.severity === "high");
  const medium = gaps.filter((g) => g.severity === "medium");

  return (
    <AppShell
      title="Institution / TPO console"
      subtitle="Co-sign student skill claims, monitor curriculum gaps, track placements."
    >
      <div className="mb-4 space-y-3">
        <ErrorNote message={error} onDismiss={() => setError(null)} />
        {toast && (
          <div className="flex items-center justify-between rounded-lg border border-emerald-200 bg-emerald-50 px-3.5 py-2.5 text-sm text-emerald-800">
            <span>✅ {toast}</span>
            <button onClick={() => setToast(null)} className="text-emerald-400">✕</button>
          </div>
        )}
        <div className="flex flex-wrap items-center gap-2 rounded-lg border border-violet-200 bg-violet-50 px-3.5 py-2 text-xs text-violet-800">
          <SyntheticTag /> students below are generated by the deterministic seeder
        </div>
      </div>

      <Tabs
        tabs={[
          { key: "queue", label: "Verification queue", count: queue.length },
          { key: "students", label: "Students", count: students.length },
          { key: "gaps", label: "Curriculum gaps", count: high.length + medium.length },
          { key: "readiness", label: "Role readiness" },
          { key: "placements", label: "Placements" },
        ]}
        active={tab}
        onChange={setTab}
      />

      <div className="mt-4">
        {tab === "queue" && (
          <Card>
            <CardHeader>
              <CardTitle>Claimed skills awaiting co-sign</CardTitle>
              <CardDescription>
                State machine: claimed → <strong>institution_cosigned (you)</strong> → verified (industry).
              </CardDescription>
            </CardHeader>
            <CardContent>
              {queue.length === 0 ? (
                <EmptyState
                  icon="✅"
                  title="Queue is clear"
                  hint="No claimed skills are waiting. New claims appear when students upload resumes with new skills."
                />
              ) : (
                <div className="space-y-2">
                  {queue.map((q) => (
                    <div key={q.id} className="flex flex-wrap items-center gap-3 rounded-lg border border-slate-100 px-3 py-2.5">
                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-center gap-2">
                          <span className="text-sm font-semibold text-slate-800">{q.label}</span>
                          <Badge>{q.category}</Badge>
                          <VerificationBadge state={q.state} />
                          {q.extracted_from_resume && <Badge tone="slate">from resume</Badge>}
                        </div>
                        <div className="mt-0.5 text-xs text-slate-500">
                          claimed by <strong>{q.full_name}</strong> · {new Date(q.claimed_at).toLocaleDateString()}
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <Button variant="outline" size="sm" onClick={() => showStudent(q.student_profile_id)}>
                          Profile
                        </Button>
                        <Button size="sm" onClick={() => cosign(q.id)} disabled={busyId === q.id}>
                          {busyId === q.id ? <Spinner /> : "Co-sign"}
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {tab === "students" && (
          <Card>
            <CardContent className="pt-4">
              {students.length === 0 ? (
                <EmptyState
                  icon="👥"
                  title="No students linked yet"
                  hint="Students appear here after they register with your institution. For the demo, re-seed from the Admin console."
                />
              ) : (
                <Table>
                  <thead>
                    <tr>
                      <TH>Student</TH>
                      <TH>Stream</TH>
                      <TH>CGPA</TH>
                      <TH>Skills</TH>
                      <TH>Verification</TH>
                      <TH></TH>
                    </tr>
                  </thead>
                  <tbody>
                    {students.map((s) => (
                      <tr key={s.id} className={openStudent === s.id ? "bg-slate-50" : ""}>
                        <TD>
                          <div className="font-medium text-slate-800">{s.full_name}</div>
                          <div className="text-[11px] text-slate-400">{s.email}</div>
                        </TD>
                        <TD>{s.stream.toUpperCase()}</TD>
                        <TD>{s.cgpa ?? "—"}</TD>
                        <TD>{s.total_skills}</TD>
                        <TD>
                          <div className="flex gap-1">
                            <Badge tone="green">● {s.verified_count}</Badge>
                            <Badge tone="blue">◔ {s.cosigned_count}</Badge>
                            <Badge tone="amber">○ {s.claimed_count}</Badge>
                          </div>
                        </TD>
                        <TD>
                          <Button variant="ghost" size="sm" onClick={() => showStudent(s.id)}>
                            {openStudent === s.id ? "Hide" : "View"}
                          </Button>
                        </TD>
                      </tr>
                    ))}
                  </tbody>
                </Table>
              )}
              {openStudent && (
                <div className="mt-4 rounded-lg border border-slate-200 bg-slate-50 p-3">
                  <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">
                    Skill ledger
                  </div>
                  <div className="flex flex-wrap gap-1.5">
                    {studentSkills.map((s) => (
                      <span key={s.id} className="inline-flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-2 py-1 text-xs">
                        {s.label} <VerificationBadge state={s.state} />
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        )}

        {tab === "gaps" && (
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <p className="text-xs text-slate-500">
                Sourced from <code>curriculum_gap_signal</code> — regenerated automatically every time an
                industry outcome is logged, plus on demand.
              </p>
              <Button
                size="sm"
                variant="outline"
                onClick={async () => {
                  const r = await api("/tpo/curriculum-gaps/refresh", { method: "POST" });
                  await loadAll();
                  setToast(`Regenerated ${r.regenerated} gap signals.`);
                }}
              >
                ↻ Regenerate
              </Button>
            </div>
            {gaps.length === 0 ? (
              <EmptyState
                icon="📡"
                title="No gap signals yet"
                hint="Signals appear once students, jobs and matches exist — or hit Regenerate."
              />
            ) : (
              <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
                {gaps.slice(0, 12).map((g) => (
                  <Card key={g.id} className={g.severity === "high" ? "border-rose-200" : g.severity === "medium" ? "border-amber-200" : ""}>
                    <CardContent className="pt-4">
                      <div className="flex items-center justify-between">
                        <span className="text-sm font-semibold text-slate-800">{g.label}</span>
                        <Badge tone={g.severity === "high" ? "red" : g.severity === "medium" ? "amber" : "slate"}>
                          {g.severity}
                        </Badge>
                      </div>
                      <div className="mt-2 grid grid-cols-3 gap-2 text-center">
                        <div>
                          <div className="text-lg font-bold text-slate-800">
                            {g.student_count ? Math.round((g.gap_count / g.student_count) * 100) : 0}%
                          </div>
                          <div className="text-[10px] uppercase text-slate-400">students missing</div>
                        </div>
                        <div>
                          <div className="text-lg font-bold text-slate-800">{g.gap_count}/{g.student_count}</div>
                          <div className="text-[10px] uppercase text-slate-400">gap count</div>
                        </div>
                        <div>
                          <div className="text-lg font-bold text-slate-800">{g.demand_score.toFixed(1)}</div>
                          <div className="text-[10px] uppercase text-slate-400">JD demand</div>
                        </div>
                      </div>
                      <Progress
                        value={g.student_count ? (g.gap_count / g.student_count) * 100 : 0}
                        className="mt-3"
                        barClassName={g.severity === "high" ? "bg-rose-500" : g.severity === "medium" ? "bg-amber-500" : "bg-slate-400"}
                      />
                      <div className="mt-1.5 text-[11px] text-slate-400">
                        demanded by {g.detail?.demanded_by_jds ?? "—"} open JDs · computed{" "}
                        {new Date(g.computed_at).toLocaleTimeString()}
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            )}
          </div>
        )}

        {tab === "readiness" && (
          <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">
            {roleGaps.length === 0 && (
              <EmptyState icon="🎯" title="No readiness data" hint="Needs students with skills in your institution." />
            )}
            {roleGaps.map((r) => (
              <Card key={r.role}>
                <CardContent className="pt-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-semibold text-slate-800">{r.role}</span>
                    <span className="text-lg font-bold text-slate-700">{pct(r.avg_readiness)}</span>
                  </div>
                  <Progress
                    value={r.avg_readiness || 0}
                    className="mt-2"
                    barClassName={(r.avg_readiness || 0) >= 65 ? "bg-emerald-500" : (r.avg_readiness || 0) >= 40 ? "bg-amber-500" : "bg-rose-500"}
                  />
                  <div className="mt-1 text-[11px] text-slate-400">{r.n_students} students assessed</div>
                  {r.missing_skill_pcts && (
                    <div className="mt-2 flex flex-wrap gap-1">
                      {r.missing_skill_pcts.slice(0, 4).map((m) => (
                        <span key={m.code} className="rounded bg-rose-50 px-1.5 py-0.5 text-[10px] text-rose-600">
                          {m.label || m.code}: {pct(m.pct_missing)} missing
                        </span>
                      ))}
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        )}

        {tab === "placements" && (
          <div className="space-y-4">
            {placements ? (
              <>
                <div className="grid grid-cols-2 gap-3 sm:grid-cols-5">
                  {[
                    ["Applications", placements.funnel.applications],
                    ["Shortlisted", placements.funnel.shortlisted],
                    ["Selected", placements.funnel.selected],
                    ["Completed", placements.funnel.completed],
                    ["Hired", placements.funnel.hired],
                  ].map(([k, v]) => (
                    <Card key={k as string}>
                      <CardContent className="pt-4 text-center">
                        <div className="text-2xl font-bold text-slate-800">{v as number}</div>
                        <div className="text-[10px] uppercase tracking-wide text-slate-400">{k as string}</div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
                <Card>
                  <CardHeader>
                    <CardTitle>Application ledger <SyntheticTag className="ml-2" /></CardTitle>
                  </CardHeader>
                  <CardContent>
                    {placements.applications.length === 0 ? (
                      <EmptyState icon="📉" title="No applications yet" hint="Students apply through their Matches tab." />
                    ) : (
                      <Table>
                        <thead>
                          <tr>
                            <TH>Student</TH>
                            <TH>Role</TH>
                            <TH>Organization</TH>
                            <TH>Match</TH>
                            <TH>Status</TH>
                            <TH>Outcome</TH>
                          </tr>
                        </thead>
                        <tbody>
                          {placements.applications.map((a: any) => (
                            <tr key={a.application_id}>
                              <TD className="font-medium text-slate-800">{a.full_name}</TD>
                              <TD>{a.title}</TD>
                              <TD>{a.organization_name}</TD>
                              <TD>{a.score != null ? a.score.toFixed(1) : "—"}</TD>
                              <TD>
                                <Badge tone={a.status === "selected" ? "green" : a.status === "rejected" ? "red" : "blue"}>
                                  {a.status}
                                </Badge>
                              </TD>
                              <TD>
                                {a.result ? (
                                  <span className="flex items-center gap-1.5">
                                    <Badge tone={a.result === "hired" ? "green" : a.result === "dropped" ? "red" : "slate"}>
                                      {a.result}
                                    </Badge>
                                    {a.performance_rating && <span className="text-amber-500">{"★".repeat(a.performance_rating)}</span>}
                                  </span>
                                ) : (
                                  "—"
                                )}
                              </TD>
                            </tr>
                          ))}
                        </tbody>
                      </Table>
                    )}
                  </CardContent>
                </Card>
              </>
            ) : (
              <div className="flex justify-center py-10"><Spinner /></div>
            )}
          </div>
        )}
      </div>
    </AppShell>
  );
}
