import { useMemo } from "react";
import { ArrowRight, CheckCircle2, Plus, Sparkles } from "lucide-react";
import SkillMap from "../../components/skills/SkillMap";
import OpportunityCard from "../../components/opportunities/OpportunityCard";
import { analyzeMatch } from "../../services/matching/matching";

export default function StudentDashboard({ skills, opportunities, onImprove, onApply }) {
  const gaps = skills.filter((skill) => skill.score < 55);
  const readiness = Math.min(95, Math.round(48 + (skills.filter((skill) => skill.score >= 55).length / skills.length) * 36));
  const matches = useMemo(() => opportunities.map((item) => [item.id, analyzeMatch(skills, item.required)]), [skills, opportunities]);
  return <div className="content" id="top"><section className="welcome"><div><p className="eyebrow">Student workspace / September 2026</p><h1>Good morning, Aarav.</h1><p className="subcopy">Your next opportunity is closer than it looks. Here is your readiness snapshot.</p></div><button className="primary-button"><Plus size={16} />Take skill assessment</button></section>
    <section className="readiness-panel"><div className="readiness-copy"><p className="eyebrow">Industry readiness</p><h2>{readiness}<small>/100</small></h2><p>{gaps.length ? "Two focused skills could unlock more roles." : "Your core skills are covered. Build portfolio proof next."}</p><a href="#skill-map">View full skill analysis <ArrowRight size={14} /></a></div><div className="readiness-orbit"><div>{readiness}<small>READY</small></div></div><div className="readiness-breakdown"><Metric label="Profile strength" value={88} /><Metric label="Skill coverage" value={Math.round((skills.filter((s) => s.score >= 55).length / skills.length) * 100)} /><Metric label="Portfolio signals" value={61} /></div></section>
    <section className="dashboard-grid"><article className="panel" id="skill-map"><div className="panel-heading"><div><p className="eyebrow">Skill intelligence</p><h2>Your skill map</h2></div><button className="text-button">Update evidence <ArrowRight size={14} /></button></div><p className="quiet">Select a skill to add new confidence evidence.</p><SkillMap skills={skills} onImprove={onImprove} /><div className="gap-callout"><Sparkles size={20} /><div><strong>{gaps.length} high-impact gap{gaps.length !== 1 ? "s" : ""} found</strong><p>{gaps.map((skill) => skill.name).join(" and ")} appear in your strongest opportunity matches.</p></div><a href="#learning-path">Explore path <ArrowRight size={14} /></a></div></article><article className="panel momentum"><div className="panel-heading"><div><p className="eyebrow">This week</p><h2>Momentum</h2></div><span className="metric-up">+2</span></div><div className="momentum-number"><strong>4</strong><span>actions<br />completed</span></div><div className="week-chart">{[28, 52, 40, 83, 46, 20, 12].map((height, index) => <span className={index === 3 ? "today" : ""} style={{ height: `${height}%` }} key={index} />)}</div><div className="days">{"MTWTFSS".split("").map((day, index) => <span className={index === 3 ? "today-label" : ""} key={`${day}${index}`}>{day}</span>)}</div><div className="next-action"><CheckCircle2 size={19} /><div><small>Next best action</small><strong>Complete Docker foundations</strong></div><ArrowRight size={17} /></div></article></section>
    <section className="opportunity-section" id="opportunities"><div className="section-heading"><div><p className="eyebrow">Curated for you</p><h2>Opportunities with a strong fit</h2><p className="quiet">Every recommendation explains its skill alignment.</p></div><button className="text-button">Browse all <ArrowRight size={14} /></button></div><div className="opportunity-grid">{opportunities.map((opportunity) => <OpportunityCard key={opportunity.id} opportunity={opportunity} match={matches.find(([id]) => id === opportunity.id)[1]} onApply={onApply} />)}</div></section>
    <section className="learning-section" id="learning-path"><div><p className="eyebrow">Targeted learning</p><h2>Close the gaps that matter.</h2><p className="quiet">A short, role-aware path to your strongest matches.</p></div><div className="learning-steps"><Step phase="NOW" title="Docker foundations" detail="3 hours" active /><Step phase="NEXT" title="AWS cloud essentials" detail="6 hours" /><Step phase="THEN" title="Deploy a full-stack project" detail="Portfolio project" /></div></section></div>;
}

function Metric({ label, value }) { return <div><span>{label}</span><strong>{value}%</strong><i><b style={{ width: `${value}%` }} /></i></div>; }
function Step({ phase, title, detail, active }) { return <div className={`learning-step ${active ? "active" : ""}`}><small>{phase}</small><strong>{title}</strong><span>{detail}</span></div>; }
