/**
 * In-memory Store and Demo State
 * Used when running in demo/offline mode or testing without an active MongoDB connection.
 */

export const store = {
  users: [
    { id: "usr_student", name: "Aarav Patel", email: "aarav@skillbridge.edu", role: "student" },
    { id: "usr_industry", name: "Elena Chen", email: "elena@northstarlabs.io", role: "industry", company: "Northstar Labs" },
    { id: "usr_inst", name: "Dr. Arvind Sharma", email: "arvind@nexus.edu", role: "institution", institution: "Nexus University" },
    { id: "usr_fac", name: "Prof. Sunita Rao", email: "sunita@nexus.edu", role: "faculty", department: "Computer Science" },
  ],

  students: [
    {
      id: "std_aarav",
      userId: "usr_student",
      name: "Aarav Patel",
      program: "B.Tech Computer Science & Engineering",
      department: "CSE",
      graduationYear: 2026,
      cgpa: 8.4,
      institution: "Nexus University",
      skills: [
        { name: "JavaScript", proficiency: 88, category: "Frontend" },
        { name: "React", proficiency: 81, category: "Frontend" },
        { name: "Node.js", proficiency: 70, category: "Backend" },
        { name: "MongoDB", proficiency: 64, category: "Databases" },
        { name: "Docker", proficiency: 24, category: "DevOps & Cloud" },
        { name: "AWS", proficiency: 17, category: "DevOps & Cloud" },
      ],
      projects: [
        {
          id: "prj_1",
          title: "Ayush Care Telemedicine Portal",
          description: "Full-stack patient booking and prescription management web application with React and Node.js.",
          skills: ["React", "JavaScript", "Node.js", "MongoDB"],
          githubUrl: "https://github.com/aarav/ayush-telecare",
        },
        {
          id: "prj_2",
          title: "Ayurvedic Formulation Search",
          description: "Indexed herb database with rapid fuzzy search and compound interaction checker.",
          skills: ["JavaScript", "React"],
          githubUrl: "https://github.com/aarav/ayur-search",
        },
      ],
      certifications: [
        {
          id: "crt_1",
          title: "Full Stack Web Development",
          issuer: "Coursera / Meta",
          issuedYear: 2025,
        },
      ],
    },
    {
      id: "std_nisha",
      name: "Nisha Rao",
      program: "B.Tech Information Technology",
      department: "IT",
      graduationYear: 2026,
      cgpa: 8.9,
      institution: "Nexus University",
      skills: [
        { name: "React", proficiency: 84 },
        { name: "JavaScript", proficiency: 90 },
        { name: "AWS", proficiency: 78 },
        { name: "Docker", proficiency: 72 },
      ],
      projects: [],
      certifications: [],
    },
    {
      id: "std_zoya",
      name: "Zoya Khan",
      program: "BCA Computer Applications",
      department: "Computer Applications",
      graduationYear: 2027,
      cgpa: 7.8,
      institution: "Nexus University",
      skills: [
        { name: "React", proficiency: 76 },
        { name: "JavaScript", proficiency: 80 },
        { name: "MongoDB", proficiency: 70 },
      ],
      projects: [],
      certifications: [],
    },
  ],

  opportunities: [
    {
      id: "northstar",
      company: "Northstar Labs",
      initials: "N",
      color: "lavender",
      role: "Frontend Engineering Intern",
      type: "internship",
      location: "Remote",
      stipend: "₹25,000 / month",
      requiredSkills: ["React", "JavaScript", "Node.js", "Docker"],
      eligibility: { minimumCgpa: 7.0, graduationYears: [2026, 2027] },
      deadline: "6 days",
      description: "Build accessible, responsive UI dashboards and interactive workflows for industry analytics products.",
      isPublished: true,
    },
    {
      id: "ayush-informatics",
      company: "National Ayush Research Hub",
      initials: "A",
      color: "emerald",
      role: "Health Informatics Research Intern",
      type: "internship",
      location: "New Delhi / Hybrid",
      stipend: "₹28,000 / month",
      requiredSkills: ["JavaScript", "React", "Python", "Ayush Health Informatics"],
      eligibility: { minimumCgpa: 7.5, graduationYears: [2026, 2027] },
      deadline: "10 days",
      description: "Collaborate on modernizing the national herbal formulation registry and clinical trial tracking platform.",
      isPublished: true,
    },
    {
      id: "civicstack",
      company: "CivicStack",
      initials: "C",
      color: "sky",
      role: "Junior Full Stack Developer",
      type: "placement",
      location: "Bengaluru",
      stipend: "₹8.5 LPA",
      requiredSkills: ["React", "Node.js", "MongoDB", "AWS"],
      eligibility: { minimumCgpa: 7.0, graduationYears: [2026] },
      deadline: "12 days",
      description: "Engineering robust microservices and citizen-facing digital service portals with high reliability.",
      isPublished: true,
    },
    {
      id: "bloomworks",
      company: "Bloomworks",
      initials: "B",
      color: "gold",
      role: "Product Engineering Fellow",
      type: "project",
      location: "Hybrid",
      stipend: "₹30,000 / month",
      requiredSkills: ["JavaScript", "React", "MongoDB"],
      eligibility: { minimumCgpa: 6.5, graduationYears: [2026, 2027] },
      deadline: "18 days",
      description: "Sponsored industry-academia capstone building assistive digital tools for modern wellness and diagnostics.",
      isPublished: true,
    },
  ],

  assessments: [
    {
      id: "asm_docker",
      skill: "Docker",
      title: "Docker & Container Fundamentals Assessment",
      estimatedMinutes: 5,
      questions: [
        {
          id: "q1",
          prompt: "What is the primary command used to define multi-container Docker applications?",
          options: ["docker run", "docker-compose up", "docker build", "docker commit"],
          correctIndex: 1,
        },
        {
          id: "q2",
          prompt: "Which Dockerfile instruction specifies the base image to build upon?",
          options: ["RUN", "COPY", "FROM", "ENTRYPOINT"],
          correctIndex: 2,
        },
        {
          id: "q3",
          prompt: "What is a major advantage of multi-stage Docker builds?",
          options: [
            "Reduces final production image size by separating build tools from runtime",
            "Increases build RAM usage",
            "Disables caching",
            "Permits unlimited containers",
          ],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "asm_aws",
      skill: "AWS",
      title: "AWS Cloud Fundamentals Assessment",
      estimatedMinutes: 5,
      questions: [
        {
          id: "q1",
          prompt: "Which AWS service provides serverless event-driven compute?",
          options: ["Amazon EC2", "AWS Lambda", "Amazon EBS", "Amazon RDS"],
          correctIndex: 1,
        },
        {
          id: "q2",
          prompt: "What service is used for scalable object storage in AWS?",
          options: ["Amazon S3", "Amazon DynamoDB", "Amazon CloudWatch", "AWS IAM"],
          correctIndex: 0,
        },
      ],
    },
    {
      id: "asm_ayush",
      skill: "Ayush Health Informatics",
      title: "Ayush Health Informatics & Digital Standards",
      estimatedMinutes: 5,
      questions: [
        {
          id: "q1",
          prompt: "Which national digital health ecosystem framework standardizes EHRs and health registries across India including Ayush?",
          options: ["Ayushman Bharat Digital Mission (ABDM)", "IEEE 802.11", "OAuth 2.0", "ISO 9001"],
          correctIndex: 0,
        },
        {
          id: "q2",
          prompt: "What is a primary objective of Herbal Informatics in modern healthcare?",
          options: [
            "Digital cataloging and bio-interaction analysis of medicinal herbs and formulations",
            "Hardware microprocessor clock speed testing",
            "General office accounting",
            "Social media marketing",
          ],
          correctIndex: 0,
        },
      ],
    },
  ],

  applications: [
    {
      id: "app_1",
      studentId: "std_aarav",
      studentName: "Aarav Patel",
      opportunityId: "northstar",
      role: "Frontend Engineering Intern",
      company: "Northstar Labs",
      status: "reviewing",
      appliedAt: "2026-09-24",
      matchScore: 75,
    },
    {
      id: "app_2",
      studentId: "std_aarav",
      studentName: "Aarav Patel",
      opportunityId: "bloomworks",
      role: "Product Engineering Fellow",
      company: "Bloomworks",
      status: "shortlisted",
      appliedAt: "2026-09-22",
      matchScore: 100,
    },
  ],

  collaborations: [
    {
      id: "collab_1",
      title: "AI-Assisted Pulse & Prakriti Diagnostic Framework",
      type: "Research Collaboration",
      partners: ["Nexus University", "Northstar Labs", "Ministry of Ayush"],
      leadFaculty: "Prof. Sunita Rao",
      studentsInvolved: 4,
      status: "Active",
      description: "Developing machine learning algorithms to assist clinicians in objective Ayurvedic constitution assessment.",
    },
    {
      id: "collab_2",
      title: "Herbal Supply Chain Traceability with Blockchain",
      type: "Industry Project",
      partners: ["Nexus University", "CivicStack"],
      leadFaculty: "Dr. Arvind Sharma",
      studentsInvolved: 6,
      status: "Proposals Open",
      description: "Student internship cohort engineering tamper-proof provenance tracking for medicinal plant sourcing.",
    },
  ],
};
