import { useState } from "react";
import { Plus, Search, SlidersHorizontal, UsersRound } from "lucide-react";
import { studentSeed } from "../../data/demo";

export default function IndustryDashboard({ onPost }) {
  const [skill, setSkill] = useState("React");
  const [shortlisted, setShortlisted] = useState([]);
  return <div className="content role-page"><section className="welcome"><div><p className="eyebrow">Industry workspace / Northstar Labs</p><h1>Find people ready to build.</h1><p className="subcopy">Turn your requirements into transparent, skill-based candidate matches.</p></div><button className="primary-button" onClick={onPost}><Plus size={16} />Post opportunity</button></section><section className="stat-grid"><Stat label="Active opportunities" value="4" note="2 internships, 2 placements" /><Stat label="Qualified candidates" value="37" note="Across active opportunities" /><Stat label="Shortlist conversion" value="28%" note="This semester" /></section><section className="split-panel"><article className="panel"><div className="panel-heading"><div><p className="eyebrow">Candidate discovery</p><h2>Role-ready candidates</h2></div><button className="icon-outline"><SlidersHorizontal size={16} /></button></div><div className="candidate-filter"><Search size={16} /><input value={skill} onChange={(event) => setSkill(event.target.value)} aria-label="Filter candidate skills" placeholder="Filter by skill" /></div><div className="candidate-list">{studentSeed.filter((student) => student.skills.some((item) => item.toLowerCase().includes(skill.toLowerCase())) || !skill).map((student) => <div className="candidate-row" key={student.name}><span className="avatar">{student.name.split(" ").map((n) => n[0]).join("")}</span><div><strong>{student.name}</strong><small>{student.program} · {student.fit}% match</small></div><div className="candidate-skills">{student.skills.slice(0, 3).map((item) => <span key={item}>{item}</span>)}</div><button className={shortlisted.includes(student.name) ? "shortlisted" : "outline-button"} onClick={() => setShortlisted((items) => items.includes(student.name) ? items.filter((item) => item !== student.name) : [...items, student.name])}>{shortlisted.includes(student.name) ? "Shortlisted" : "Shortlist"}</button></div>)}</div></article><article className="panel requirement-panel"><p className="eyebrow">Smart automation</p><h2>Build a clearer brief.</h2><p className="quiet">Required skills are the signal that powers candidate ranking.</p><label>Role title<input defaultValue="Frontend Engineering Intern" /></label><label>Required skills<input defaultValue="React, JavaScript, Node.js, Docker" /></label><label>Eligibility<input defaultValue="2027 graduating batch · 7.0+ CGPA" /></label><button className="primary-button full" onClick={onPost}>Publish and match candidates</button></article></section></div>;
}
function Stat({ label, value, note }) { return <article className="stat-card"><small>{label}</small><strong>{value}</strong><span>{note}</span></article>; }
